# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.1"
stylua = "johnnymorganz/stylua@0.20.0"
mantle = "blake-mealey/mantle@0.11.16"
blink = "1Axen/blink@0.13.5"
lune = "lune-org/lune@0.8.6"
